# Generated by Django 3.2.25 on 2025-06-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyberbullying_detection_type',
            old_name='Tweet_text',
            new_name='tweet_text',
        ),
    ]
