# Generated by Django 3.2.25 on 2025-06-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0002_rename_tweet_text_cyberbullying_detection_type_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberbullying_detection_type',
            name='tweet_text',
            field=models.TextField(),
        ),
    ]
